### ISSUE TITLE
DBServiceActor is failing with Timeout Exception

### ISSUE THREAD

**Issue by joesan** [joesan/plant-simulator#1]
In the [DBServiceActor.scala](https://github.com/joesan/plant-simulator/blob/master/app/com/inland24/plantsim/services/database/DBServiceActor.scala),  we pre-start it by reading the DBService method to fetch all active power plants. But this message is never received in the receive block of this actor as there is no match case to pattern match this message type. 

This message needs to be processed in the receive block and the actor has to be context becomed so that successive messages are handled.

Here is the exception from the logs:

```
[INFO] [08/11/2017 13:57:59.390] [application-akka.actor.default-dispatcher-4] [akka://application/user/$a/$a] Pre-start DBServiceActor
[INFO] [08/11/2017 13:57:59.402] [application-akka.actor.default-dispatcher-4] [akka://application/user/$a/$a] done with pre-start DBServiceActor *****
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://application/user/$a/$a#-1046088460]] after [5000 ms]. Sender[Actor[akka://application/user/$a#-293595750]] sent message of type "com.inland24.plantsim.services.database.DBServiceActor$PowerPlantEvents$".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by joesan** [comment]
Kind of fixed it. So I'm now passing in the SupervisorActor reference to the DBServiceActor so that the DBServiceActor can push messages into the SupervisorActor instead of the SupervisorActor asking for events from the DBServiceActor. So this way, I can avoid any nasty timeouts!
